[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
upload_protocol = picotool
debug_tool = picoprobe
monitor_speed = 115200
lib_ldf_mode = deep+
extra_scripts = pre:trigger_bootsel.py

board_build.filesystem = littlefs
board_build.filesystem_size = 4m
board_upload.maximum_size = 16777216

lib_deps =
    adafruit/Adafruit PWM Servo Driver Library@^3.0.3
    earlephilhower/ESP8266Audio@^1.9.9